### PR TITLE
Gracefully continue if rwa and dta do not jive.

### PR DESCRIPTION
**Pull request by jillings**
This checks on the size of the rwa and dta data frames and, if they do not jive, the resultant data frame is created with size [0, 0]. 

combine.py tests on this and sets the ignore_sim flag to True so the program can continue gracefully.

### CODE REVIEW

**Comment by sviel** [comment]
I agree with implementing a check against `length_rwa != length_dta`

In such a case, I think that the program should exit with the error message, not continue as if ignore_sim had been set to true.  In other words, if the analyst wishes they may set that flag at command line, but without it we should exit to make sure the error message is noticed.

**Comment by jillings** [comment]
Simon - if the program exits with the error message, what happens to automated analysis? If there are 11 good tests and one bad tests being analyzed in a batch, surely we do not want the program to quit.

But we do want it obvious we proceeded without MVM data.

**Comment by sviel** [comment]
`process_run` is called in a `for` loop, so printing an error message this function, then `return` should work, in that it will then proceed to the next test?

**Comment by jillings** [comment]
Valerio,

I agree emphatically.

Chris

**Comment by sviel** [comment]
I have promoted print statements to `log.error`.  No plot is produced on error, so I suppose that the person running the code will then investigate and notice the conspicuous errors in the log file.  

I think this is better than producing an "error plot", which might actually make it harder for automatic jobs to find that something went wrong?

CI failed "check was cancelled" (?)  Investigating

**Comment by jillings** [comment]
Cool!

**Comment by sviel** [comment]
I'm out of ideas.  The issue might be on GitHub's end.  I'll hit the CI retry button later

**Comment by sviel** [comment]
CI builds are still unexpectedly cancelled, so I have emailed GitHub Support

"Our response time for these requests may be 7-10 days"
https://support.github.com/covid-19

but if the issue is indeed on their side, and affects all CI builds, it might be fixed faster.

**Pull request merged**
