### PR TITLE
Improve readability and information content on overlay plots.

### PR DESCRIPTION
**Pull request by jillings**
This replaces the print statement with a "Warning statement" incase the dt and integer indexing get out of sync.

Extra information added to plot.

Better aesthetics.

### CODE REVIEW

**Comment by sviel** [comment]
Thanks @jillings, the overlay plots look a little better

I'm not sure about the verbose option, in particular the HTJI parts.  What does HTJI stand for?

Also, this makes me notice that `plot_summary_canvases` and `plot_overlay_canvases` are already called within a loop currently starting on L573 in combine.py
```
    for i in range (len(meta)) :
      #for the moment only one test per file is supported here
```
... which is strange because the index i is not used in this loop.  @paoloagnes what was the intention here?  Would something like `for local_objname in meta` make more sense?

In any case, I don't see why we need other loops `for i in range(len(meta)):` in the functions in combine_plot_summary_canvases.py ?

Thank you both
Simon

**Comment by paoloagnes** [comment]
> Thanks @jillings, the overlay plots look a little better
> 
> I'm not sure about the verbose option, in particular the HTJI parts. What does HTJI stand for?
> 
> Also, this makes me notice that `plot_summary_canvases` and `plot_overlay_canvases` are already called within a loop currently starting on L573 in combine.py
> 
> ```
>     for i in range (len(meta)) :
>       #for the moment only one test per file is supported here
> ```
> 
> ... which is strange because the index i is not used in this loop. @paoloagnes what was the intention here? Would something like `for local_objname in meta` make more sense?
> 
> In any case, I don't see why we need other loops `for i in range(len(meta)):` in the functions in combine_plot_summary_canvases.py ?
> 
> Thank you both
> Simon


Hi Simon, 
it is true that with the current data taking protocol we do not need a loop on the length of meta. It was added at the beginning of testing campaign, as more than one test was present in each file, thus we had to create a dictionary entry for each test ( indexed by meta[filename_index] ). I did not get rid of all these instances in case we had to take a look at older data, but for clarity I think now it can be safely removed

**Comment by jillings** [comment]
My bad - I thought I worked on a completely clean branch from master. I put in a verbose so I could optionally print out information for me. 

I will clean it up.

HTJI stands for "Hello to Jason Isaacs". Google it if you must.

**Comment by jillings** [comment]
Paolo,

You are correct about the double loop. I followed the convention of the summary routine when I wrote mine. It was my intention to bring this up today. If we do multiple runs we will "double loop" the plots to bad effect.

**Comment by jillings** [comment]
I just pushed code with the verbose printing removed and the overlay plot taken out of (both) loops of meta.

**Comment by jillings** [comment]
Will clean up merge conflicts...

**Comment by jillings** [comment]
merge conflicts resolved.

**Comment by sviel** [comment]
Thank you Chris, I think we can clean this up further, following confirmation by Paolo.  It's easier to implement myself than to explain, so I'll do that

**Comment by sviel** [comment]
Done

**Comment by jillings** [comment]
What is the status of this branch? I need the information I put on the plot. If I merge in my branch into where I am working now, will it cause merge conflicts down the road?

**Comment by sviel** [comment]
Yes - I'm going to resolve the merge conflicts now

**Comment by sviel** [comment]
Alright, now you may merge this branch into your other branch.  It means that this will have to be merged into master before your new work; as it's essentially ready I see no problem

**Comment by jillings** [comment]
Thanks. I found a work around This plot is very useful for me.

**Comment by sviel** [comment]
I have fixed merge conflicts again,
and changed back Warning declarations to print statements (turns out the former doesn't print)

**Pull request merged**
