### PR TITLE
Compare two tests

### PR DESCRIPTION
**Pull request by 70rc**
There's still room for improvement. For instance there's a lot of redundancy with combine.py. If process_run could be streamlined not to include plotting, but just processing as its name suggests, it could be called directly from compare.py without the need to partially replicate it.

### CODE REVIEW

**Comment by sviel** [comment]
Good idea Damian @70rc 
Would you like to try moving the duplicate code from `process_run` to another function in a common file?
Also, I think that `columns_rwa` and `columns_dta` could be moved to mvmio.py

**Comment by vippolit** [comment]
> There's still room for improvement. For instance there's a lot of redundancy with combine.py. If process_run could be streamlined not to include plotting, but just processing as its name suggests, it could be called directly from compare.py without the need to partially replicate it.

I strongly support this, the more modular the better

**Comment by 70rc** [comment]
I'm happy to do that. I see that you already started this effort in https://github.com/MechanicalVentilatorMilano/MVMAnalysis/pull/24 @sviel Maybe I'll wait for this to be merged, or is it independent?

**Comment by sviel** [comment]
It's independent, for modular process methods I suggest to create a new python file

Thanks!

**Comment by 70rc** [comment]
I'm closing this for now. Without further modularisation, I'm constantly chasing ghosts by trying to keep in sync with the rest of the code.

**Pull request closed without merging**
